config:
  nacos:
    - id: test-windows
      server_addr: 172.27.10.16:8848,172.27.10.17:8848,172.27.10.18:8848
      namespace: 59025239-e2a7-4f5d-856f-e04356f7f043
      username: nacos
      password: nacos
      group: DEFAULT_GROUP
      property_names:
        - aaaa.yaml
      file_path: "D:"
      command: echo "Hello, Nacos! windows"
discovery:
  nacos:
    - id: test-windows
      server_addr: 172.27.10.16:8848,172.27.10.17:8848,172.27.10.18:8848
      namespace: 59025239-e2a7-4f5d-856f-e04356f7f043
      username: nacos
      password: nacos
      group: DEFAULT_GROUP
      template:
      refresh_interval: 5s
      service_names:
        - aaaa.yaml
      file_path: "D:"
      command: echo "Hello, Nacos! windows"
